version: 0.2

phases:
  install:
    commands:
      - echo "Installing composer if missing"
      - if ! command -v composer >/dev/null 2>&1; then curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer; fi
      - composer --version || true
      - node -v || true
      - npm -v || true

  pre_build:
    commands:
      - echo "Preparing env"
      - cp .env.example .env || true
      - echo "Installing PHP dependencies"
      - composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

  build:
    commands:
      - echo "Building the app"
      - npm install
      - npm run build || true

  post_build:
    commands:
      - echo "Packaging artifact"
      - mkdir -p deploy
      - cp -r * deploy/
      - cp appspec.yml deploy/appspec.yml
      - cp -r scripts deploy/scripts

artifacts:
  files:
    - deploy/**/*
