version: 0.2

env:
  variables:
    APP_ENV: production
    APP_DEBUG: "false"
    COMPOSER_HOME: /tmp/composer

phases:
  install:
    commands:
      - echo "Prepare COMPOSER_HOME at $COMPOSER_HOME and ensure writable"
      - mkdir -p "$COMPOSER_HOME"
      - chmod 1777 "$COMPOSER_HOME" || true
      - echo "Installing composer if missing"
      - |
        if ! command -v composer >/dev/null 2>&1; then
          curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
        fi
      - echo "Composer version (using forced COMPOSER_HOME=$COMPOSER_HOME)"
      - COMPOSER_HOME=$COMPOSER_HOME composer --version || true
      - node -v || true
      - npm -v || true

  pre_build:
    commands:
      - echo "Preparing .env (do NOT store secrets in repo) - inject in deploy targets"
      - cp .env.example .env || true
      - echo "Installing PHP dependencies (production) with forced COMPOSER_HOME"
      - COMPOSER_HOME=$COMPOSER_HOME composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-ansi

  build:
    commands:
      - echo "Build frontend (if applicable)"
      # Safe npm handling: prefer npm ci when lockfile exists, otherwise fallback to npm install
      - |
        if [ -f package.json ]; then
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "Lockfile found — running npm ci"
            npm ci
          else
            echo "No lockfile — running npm install (this will generate a lockfile)"
            npm install
          fi

          # Run build if a build script is defined
          if npm run | grep -q " build"; then
            npm run build || true
          else
            echo "No npm build script defined, skipping npm run build"
          fi
        else
          echo "No package.json — skipping frontend build"
        fi
      - echo "Performing artisan optimization (safe-fail if not applicable)"
      - php artisan config:cache || true
      - php artisan route:cache || true
      - php artisan view:cache || true

  post_build:
    commands:
      - echo "Packaging artifact"
      - mkdir -p build_output
      - rsync -av --exclude='.git' --exclude='node_modules' --exclude='.env' --exclude='storage/logs/*' ./ build_output/
      - cd build_output
      - zip -r ../laravel-deploy.zip .
      - cd ..
      - ls -lh laravel-deploy.zip || true

artifacts:
  files:
    - 'laravel-deploy.zip'
  discard-paths: yes

cache:
  paths:
    - '/root/.composer/cache/**'
    - 'node_modules/**'
